### ISSUE TITLE
[Bug] [zos_job_submit] Incorrect display of DD byte_count

### ISSUE THREAD

**Issue by gngrossi** [ansible-collections/ibm_zos_core#1508]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Bug description

The job is submitted, runs and the the output is proper except for the DD byte_counts are not matching with what's on JES spool.

### IBM z/OS Ansible core Version

v1.9.0

### IBM Z Open Automation Utilities

v1.2.5 (default)

### IBM Enterprise Python

v3.11.x (default)

### ansible-version

v2.16.x (default)

### z/OS version

v2.5 (default)

### Ansible module

zos_job_submit

### Playbook verbosity output.

  - name: Print DDs from Job {{jobname}} stats
    debug:
      msg:
        - "{{jobdds[item | int].ddname}}"
        - "{{jobdds[item | int].id}}"
        - "{{jobdds[item | int].record_count}}"
        - "{{jobdds[item | int].stepname}}"
        - "{{jobdds[item | int].byte_count}}"
    with_sequence: start=0 end="{{jobddl | int-1}}"

Ansible output
![image](https://github.com/ansible-collections/ibm_zos_core/assets/115715798/e590797b-d49a-434d-b430-48e1b59cde55)

JES spool
![image](https://github.com/ansible-collections/ibm_zos_core/assets/115715798/fd1d0f32-4adc-4fe2-a62c-ce676d08d56b)

**Comment by gngrossi** [comment]
Still an issue with ibm.ibm_zos_core:==1.10.0-beta.1 and zoau 1311 and python 3.12.1

**Comment by ddimatos** [comment]
Looks like we used to access it via SDSF REXX `JDS_BYTECNT`, after the migration to ZOAU , someone calculated it incorrectly with `dd["byte_count"] = single_dd["record_length"]`.

**Comment by gngrossi** [comment]
@ddimatos Any additional documentation needed?
thanks

**Comment by ddimatos** [comment]
@gngrossi - not at the moment, I am currently look for an efficient way to calculate this and most everything I am coming up with has some sort of corner case and of course performance or introduces a new dependency if we do it in Ansible. 

The solution I like the most is to open a enhancement request on ZOAU and have them using the z/OS MVS Subsystem Interface because then they are reading a control block, its efficient and removes the corner cases when trying to calculate this but I would not expect this to be available till the end of the year. Thus this would have to be handled as a known issue.

Could you tell me the use case for the `Byte-cnt`, I personally don't use it but curious how others use it.

**Comment by gngrossi** [comment]
@ddimatos Sorry, I don't have a real use case for the byte count data. IMO, if it's going to be available as a statistic, then it should be accurate otherwise it leads to asking the question "what else isn't right?"

In this example, I was interested in seeing the results of using JES spool data encryption which includes compression. 

![image](https://github.com/ansible-collections/ibm_zos_core/assets/115715798/1529a9e8-0242-45ed-833f-0222ad60fe03)

![image](https://github.com/ansible-collections/ibm_zos_core/assets/115715798/3c1effd5-782f-4718-91c1-dbcf9d90ff45)

 thanks

**Comment by ddimatos** [comment]
Understood, we should include a few statistical test cases ensuring accuracy, I'll continue to look into this, this helps, we also want the same.

**Comment by richp405** [comment]
Related to Jira 10606 - Zoau estimates 3rd or 4th qtr fix

**Comment by ddimatos** [comment]
I went through various options, to handle this in Ansible none of those are efficient and without possible corner case issues, I will add this as a known issue to our release notes and wait for ZOAUs change that can access the control block in an efficient and accurate way.

**Comment by fernandofloresg** [comment]
ZOAU has fixed this in 1.3.4, and the fix is now planned for 2025.Q1 v1.14.0-beta.1

**Comment by richp405** [comment]
I will validate the correction and make sure it flows through zos core this week.

**Comment by richp405** [comment]
I've manually verified in Zoau 1.3.x, prior to 4, the size field is not there.  In 1.3.4, the numbers shown in the json output are correct.   Tomorrow I'll run this against zos core, but my expectation is we WILL need to make adaptation in 1.14 to use the new field.

**Comment by fernandofloresg** [comment]
Fixed by #1868

**Comment by gngrossi** [comment]
Still not seeing the correct DD byte count.
What am I missing?
thanks

![Image](https://github.com/user-attachments/assets/40307dad-aecc-49f2-a6b2-550b3532f351)
